apiVersion: v1
kind: Service
metadata:
 name: hello-world-app-deployment
spec:
 selector:
   app: hello-world-app
 ports:
 - port: 3000
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer